INSERT INTO `carried_medications` (`uuid`, `drone_uuid`, `medication_uuid`, `quantity`)
VALUES (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D-441-05' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M-432-512-547-05' LIMIT 1),
        1),
       (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D-441-05' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M-432-512-547-04' LIMIT 1),
        2),
       (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D-441-07' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M-432-512-547-03' LIMIT 2),
        1),
       (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D-441-03' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M-432-512-547-05' LIMIT 1),
        4);
