INSERT INTO `carried_medications` (`uuid`, `drone_uuid`, `medication_uuid`, `quantity`)
VALUES (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D_441_05' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M_432_512_547_05' LIMIT 1),
        1),
       (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D_441_05' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M_432_512_547_04' LIMIT 1),
        2),
       (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D_441_07' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M_432_512_547_03' LIMIT 2),
        1),
       (UUID(),
        (SELECT `uuid` from `drones` where `serial_number` = 'D_441_03' LIMIT 1),
        (SELECT `uuid` from `medications` where `code` = 'M_432_512_547_05' LIMIT 1),
        4);
